#!groovy

// Generated by IBM TransformationAdvisor
// Fri Apr 05 08:07:44 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'customerorderservicesapp'
    mvnCommands = '--version'
    test='false'
}